from functools import partial

from domain.entities.consumables import Consumable
from domain.entities.item import Item
from domain.entities.scroll import Scroll
from domain.entities.weapon import Weapon
from domain.value_objects.enums import (
    ConsumableType,
    ItemType,
    TreasureType,
    WeaponType,
)

CONSUMABLE_TEMPLATES = {
    (ItemType.CONSUMABLE, ConsumableType.HEALTH): partial(
        Consumable,
        subtype=ConsumableType.HEALTH,
        name="Healing Potion",
        description="Restores 20 HP",
        health=20,
        max_health=0,
        dexterity=0,
        strength=0,
        value=5,
    ),
    (ItemType.CONSUMABLE, ConsumableType.MAX_HEALTH): partial(
        Consumable,
        subtype=ConsumableType.MAX_HEALTH,
        name="Potion of Vitality",
        description="Permanently increases max HP by 20",
        health=0,
        max_health=20,
        dexterity=0,
        strength=0,
        value=15,
    ),
    (ItemType.CONSUMABLE, ConsumableType.STRENGTH): partial(
        Consumable,
        subtype=ConsumableType.STRENGTH,
        name="Elixir of Strength",
        description="Permanently increases strength by 8",
        health=0,
        max_health=0,
        dexterity=0,
        strength=8,
        value=8,
    ),
    (ItemType.CONSUMABLE, ConsumableType.MAX_STRENGTH): partial(
        Consumable,
        subtype=ConsumableType.MAX_STRENGTH,
        name="Draught of Power",
        description="Permanently increases strength by 12",
        health=0,
        max_health=0,
        dexterity=0,
        strength=12,
        value=18,
    ),
    (ItemType.CONSUMABLE, ConsumableType.DEXTERITY): partial(
        Consumable,
        subtype=ConsumableType.DEXTERITY,
        name="Elixir of Dexterity",
        description="Permanently increases dexterity by 8",
        health=0,
        max_health=0,
        dexterity=8,
        strength=0,
        value=8,
    ),
    (ItemType.CONSUMABLE, ConsumableType.MAX_DEXTERITY): partial(
        Consumable,
        subtype=ConsumableType.MAX_DEXTERITY,
        name="Draught of Agility",
        description="Permanently increases dexterity by 12",
        health=0,
        max_health=0,
        dexterity=12,
        strength=0,
        value=18,
    ),
    (ItemType.CONSUMABLE, ConsumableType.FOOD): partial(
        Consumable,
        subtype=ConsumableType.FOOD,
        name="Food Ration",
        description="Restores 10 HP",
        health=10,
        max_health=0,
        dexterity=0,
        strength=0,
        value=3,
    ),
}

WEAPON_TEMPLATES = {
    (ItemType.WEAPON, WeaponType.DAGGER): partial(
        Weapon,
        subtype=WeaponType.DAGGER,
        name="Dagger",
        description="A short, quick blade",
        damage=8,
        value=15,
    ),
    (ItemType.WEAPON, WeaponType.MACE): partial(
        Weapon,
        subtype=WeaponType.MACE,
        name="Mace",
        description="A heavy blunt weapon",
        damage=12,
        value=25,
    ),
    (ItemType.WEAPON, WeaponType.SWORD): partial(
        Weapon,
        subtype=WeaponType.SWORD,
        name="Iron Sword",
        description="A sturdy iron sword",
        damage=15,
        value=50,
    ),
    (ItemType.WEAPON, WeaponType.SPEAR): partial(
        Weapon,
        subtype=WeaponType.SPEAR,
        name="Spear",
        description="A long thrusting weapon",
        damage=14,
        value=30,
    ),
    (ItemType.WEAPON, WeaponType.AXE): partial(
        Weapon,
        subtype=WeaponType.AXE,
        name="War Axe",
        description="A brutal axe",
        damage=18,
        value=45,
    ),
    (ItemType.WEAPON, WeaponType.TWO_HANDED_SWORD): partial(
        Weapon,
        subtype=WeaponType.TWO_HANDED_SWORD,
        name="Greatsword",
        description="A massive sword for powerful strikes",
        damage=25,
        value=80,
    ),
    (ItemType.WEAPON, WeaponType.STAFF): partial(
        Weapon,
        subtype=WeaponType.STAFF,
        name="Magic Staff",
        description="Channels arcane power",
        damage=12,
        value=40,
    ),
}

TREASURE_TEMPLATES = {
    (ItemType.TREASURE, TreasureType.COINS): partial(
        Item,
        type=ItemType.TREASURE,
        subtype=TreasureType.COINS,
        name="Gold Coins",
        description="Shiny gold coins",
        value=10,
    ),
    (ItemType.TREASURE, TreasureType.SILVER): partial(
        Item,
        type=ItemType.TREASURE,
        subtype=TreasureType.SILVER,
        name="Silver Coins",
        description="Shiny silver coins",
        value=5,
    ),
    (ItemType.TREASURE, TreasureType.GEM): partial(
        Item,
        type=ItemType.TREASURE,
        subtype=TreasureType.GEM,
        name="Gemstone",
        description="A sparkling gemstone",
        value=30,
    ),
    (ItemType.TREASURE, TreasureType.RUBY): partial(
        Item,
        type=ItemType.TREASURE,
        subtype=TreasureType.RUBY,
        name="Ruby",
        description="A precious ruby",
        value=50,
    ),
    (ItemType.TREASURE, TreasureType.SAPPHIRE): partial(
        Item,
        type=ItemType.TREASURE,
        subtype=TreasureType.SAPPHIRE,
        name="Sapphire",
        description="A brilliant sapphire",
        value=60,
    ),
}

SCROLL_TEMPLATES = {
    (ItemType.SCROLL, ConsumableType.STRENGTH): partial(
        Scroll,
        subtype=ConsumableType.STRENGTH,
        name="Scroll of Strength",
        description="Permanently increases strength by 5",
        health=0,
        max_health=0,
        dexterity=0,
        strength=5,
        value=12,
    ),
    (ItemType.SCROLL, ConsumableType.MAX_STRENGTH): partial(
        Scroll,
        subtype=ConsumableType.MAX_STRENGTH,
        name="Scroll of Power",
        description="Permanently increases strength by 10",
        health=0,
        max_health=0,
        dexterity=0,
        strength=10,
        value=20,
    ),
    (ItemType.SCROLL, ConsumableType.DEXTERITY): partial(
        Scroll,
        subtype=ConsumableType.DEXTERITY,
        name="Scroll of Agility",
        description="Permanently increases dexterity by 5",
        health=0,
        max_health=0,
        dexterity=5,
        strength=0,
        value=12,
    ),
    (ItemType.SCROLL, ConsumableType.HEALTH): partial(
        Scroll,
        subtype=ConsumableType.HEALTH,
        name="Scroll of Healing",
        description="Restores 30 HP",
        health=30,
        max_health=0,
        dexterity=0,
        strength=0,
        value=8,
    ),
    (ItemType.SCROLL, ConsumableType.MAX_HEALTH): partial(
        Scroll,
        subtype=ConsumableType.MAX_HEALTH,
        name="Scroll of Vitality",
        description="Permanently increases max HP by 15",
        health=0,
        max_health=15,
        dexterity=0,
        strength=0,
        value=18,
    ),
}

ITEM_TEMPLATES = {}
ITEM_TEMPLATES.update(CONSUMABLE_TEMPLATES)
ITEM_TEMPLATES.update(WEAPON_TEMPLATES)
ITEM_TEMPLATES.update(TREASURE_TEMPLATES)
ITEM_TEMPLATES.update(SCROLL_TEMPLATES)
